name: ShadowSMP
version: '1.1'
main: me.nickotato.shadowSMP.ShadowSMP
api-version: '1.21'
commands:
  ability:
    description: Use your ghost's ability
    permission: ""
  ultimate:
    description: Use your ghost's ultimate
    permission: ""
  charm_ability:
    description: Use your charm's ability
    permission: ""
  give_charms:
    description: Open the charms gui
    permission: ShadowSMP.give_charms
  withdraw_charm:
    description: Withdraws your charm
    permission: ""
  give_shadow_items:
    description: Opens the shadow items gui
    permission: ShadowSMP.give_shadow_items
  reset_cooldown:
    description: Resets the users cooldown
    permission: ShadowSMP.reset_cooldown
  manage:
    description: "Manage Players"
    permission: ShadowSMP.manage
  souls:
    description: "View the amount of souls you have"
    permission: ""
    usage: /souls
  withdraw_soul:
    description: "Withdraw one soul"
    permission: ""
    usage: /withdraw_soul
  withdraw_upgrader:
    description: "Withdraw your upgrader"
    permission: ""
  check_revenant:
    description: "Check if Revenant is working for a player"
    permission: ShadowSMP.check_revenant
  restarting_in:
    description: "Sends a message to everyone saying the server is restarting"
    permission: ShadowSMP.restarting_in
  ghost:
    description: "Check what ghost you have and it's abilities"
    permission: ""
  config:
    description: "Open the config for shadow smp"
    permission: ShadowSMP.config